### ISSUE TITLE
/dcd occasionally displays > 2 decimal values

### ISSUE THREAD

**Issue by Iotados** [DogcraftNet/Server-BugTracker#1]
![image](https://user-images.githubusercontent.com/76396089/182248563-7df32d97-1b5b-4c78-8824-1efb880f33ae.png)

Affected world: Shepherd reported 

Occasionally the /dcd command presents an exorbitantly large number, instead of showing the normal 2 decimal place figure. As seen in image above - that is 13 decimal places for reference - others have reported similar issues though with various decimal places.

**Comment by ironboundred** [comment]
Should be fixed in the previouse restart.

**Comment by Iotados** [comment]
Been 13 days without any report of this happening again, assuming that it was indeed fixed!
